name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.authorized_keys }}" > "$HOME/.ssh/authorized_keys"
      - run: chmod 600 "$HOME/.ssh/authorized_keys"
      # Deploy
      - run: rsync -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . olider_db@45.146.165.53:LupenBot/
